server:
  port: 8182

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miniassignment2?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


app:
  randomUserUrl: https://randomuser.me
  NationalityUrl: https://api.nationalize.io
  genderUrl: https://api.genderize.io

